version: '3.7'
services:
  web_scraper:
    container_name: scraper
    ports: 
      - "4444:4444"
    build: ./webscraper
    volumes:
      - ./webscraper:/usr/src/app
    links:
      - chromedriver