version: '3.7'
services:
  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444
  web_scraper:
    container_name: scraper
    build: ./webscraper
    volumes:
      - ./webscraper:/app
    depends_on:
      - selenium